# Site settings
title: Peter Cutler
email: petergcutler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Peter Cutler's website. Based in DC.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "petergcutler.github.io" # the base hostname & protocol for your site
twitter_username: petergcutler
github_username:  petergcutler

# Build settings
markdown: kramdown

collections:

 writing:
  output: true
  permalink: /writing/:path/

 projects:
  output: true
  permalink: /projects/:path/
